server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 192.168.150.101
      port: 6379
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.101:8848
  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: admin
    password: admin

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

rabbitmq:
  queue:
    stats-save: short-link.stats.queue.actual  # 这里的配置会覆盖代码里的默认值
  exchange:
    stats-save: short-link.stats.exchange.actual
  routing-key:
    stats-save: short-link.stats.routing-key.actual